### ISSUE TITLE
Broken Link on README file 

### ISSUE THREAD

**Issue by Ariel-Isaacm** [Atemosta/feh-gauntlet-bot#10]
The link https://mtfalls.github.io/projects/feh-gauntlet-bot/ shown on the readme file is redirecting to a 404

**Comment by OhKairos** [comment]
I never got an alert for this LOL

I can fix that after the next feature rollout where we migrate from Twitter to Discord.

**Comment by OscarKevinXR** [comment]
forgot to close, thanks for submitting this issue @Ariel-Isaacm :)
