### ISSUE TITLE
Kubernetes: Secrets Management

### ISSUE THREAD

**Issue by OscarKevinXR** [Atemosta/feh-gauntlet-bot#20]
Hashicorp? 

https://www.vaultproject.io/downloads

https://www.digitalocean.com/community/tutorials/how-to-securely-manage-secrets-with-hashicorp-vault-on-ubuntu-16-04

**Comment by OhKairos** [comment]
vault is overkill for this use case for now 

will explore k8s secrets in future issue #14 https://kubernetes.io/docs/concepts/configuration/secret/

**Comment by OscarKevinXR** [comment]
No longer required
