### ISSUE TITLE
Modernize to Serverless Architecture 

### ISSUE THREAD

**Issue by Ousikai** [Atemosta/feh-gauntlet-bot#7]
- Rename gauntlet_template.py to gauntlet_alert.py
- Create function to dynamically determine WHO is competing in a round 
- Create lambda function for gauntlet_alert.py
- Create cloudwatch alarm to trigger lambda function
- Use AWS CI/CD to automatically update lambda function with new assets, code updates, and time of competition

**Comment by mtfallsVR** [comment]
Including #9 as part of requisites

**Comment by Ousikai** [comment]
ultimately decided on microapps model to be migrated to kubernetes
